# Generated by Django 5.2.4 on 2025-08-06 09:31

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AdditionalService",
            fields=[
                ("service_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("per_room", "Per Room"),
                            ("per_person", "Per Person"),
                        ],
                        default="per_room",
                        max_length=20,
                    ),
                ),
                (
                    "description",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "additional_services",
            },
        ),
        migrations.CreateModel(
            name="Province",
            fields=[
                ("province_id", models.AutoField(primary_key=True, serialize=False)),
                ("province_name", models.CharField(max_length=30)),
                ("province_code", models.CharField(max_length=30)),
            ],
            options={
                "db_table": "provinces",
            },
        ),
        migrations.CreateModel(
            name="Role",
            fields=[
                ("role_id", models.AutoField(primary_key=True, serialize=False)),
                ("role_name", models.CharField(max_length=30)),
                (
                    "description",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
            ],
            options={
                "db_table": "roles",
            },
        ),
        migrations.CreateModel(
            name="SystemSettings",
            fields=[
                (
                    "setting_key",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("setting_value", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "system_settings",
            },
        ),
    ]
