# Generated by Django 5.2.4 on 2025-08-07 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appartment", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ElectricWaterTotal",
            fields=[
                ("total_id", models.AutoField(primary_key=True, serialize=False)),
                ("summary_for_month", models.DateTimeField()),
                ("total_electricity", models.IntegerField()),
                ("total_water", models.IntegerField()),
                (
                    "electricity_cost",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("water_cost", models.DecimalField(decimal_places=2, max_digits=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "electric_water_totals",
            },
        ),
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "room_id",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                (
                    "area",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("available", "Available"),
                            ("occupied", "Occupied"),
                            ("maintenance", "Maintenance"),
                        ],
                        default="available",
                        max_length=20,
                    ),
                ),
                ("max_occupants", models.IntegerField(default=5)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "rooms",
            },
        ),
        migrations.CreateModel(
            name="District",
            fields=[
                ("district_id", models.AutoField(primary_key=True, serialize=False)),
                ("district_name", models.CharField(max_length=30)),
                ("district_code", models.CharField(max_length=30)),
                (
                    "province",
                    models.ForeignKey(
                        db_column="province_id",
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="appartment.province",
                    ),
                ),
            ],
            options={
                "db_table": "districts",
            },
        ),
        migrations.CreateModel(
            name="Ward",
            fields=[
                ("ward_id", models.AutoField(primary_key=True, serialize=False)),
                ("ward_name", models.CharField(max_length=30)),
                ("ward_code", models.CharField(max_length=30)),
                (
                    "district",
                    models.ForeignKey(
                        db_column="district_id",
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="appartment.district",
                    ),
                ),
            ],
            options={
                "db_table": "wards",
            },
        ),
    ]
