# Generated by Django 5.2.4 on 2025-08-07 13:52

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appartment", "0002_electricwatertotal_room_district_ward"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "user_id",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("full_name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=50, unique=True)),
                ("phone", models.CharField(max_length=20)),
                (
                    "detail_address",
                    models.CharField(blank=True, max_length=55, null=True),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_staff", models.BooleanField(default=False)),
                ("is_superuser", models.BooleanField(default=False)),
                (
                    "date_joined",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "district",
                    models.ForeignKey(
                        blank=True,
                        db_column="district_id",
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="appartment.district",
                    ),
                ),
                (
                    "province",
                    models.ForeignKey(
                        blank=True,
                        db_column="province_id",
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="appartment.province",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        db_column="role_id",
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="appartment.role",
                    ),
                ),
                (
                    "ward",
                    models.ForeignKey(
                        blank=True,
                        db_column="ward_id",
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="appartment.ward",
                    ),
                ),
            ],
            options={
                "db_table": "users",
            },
        ),
    ]
