# Generated by Django 5.2.4 on 2025-07-31 07:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appartment', '0002_user_date_joined_user_is_active_user_is_staff_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElectricWaterTotal',
            fields=[
                ('total_id', models.AutoField(primary_key=True, serialize=False)),
                ('summary_for_month', models.DateTimeField()),
                ('total_electricity', models.IntegerField()),
                ('total_water', models.IntegerField()),
                ('electricity_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('water_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'electric_water_totals',
            },
        ),
        migrations.CreateModel(
            name='ElectricWaterService',
            fields=[
                ('service_id', models.AutoField(primary_key=True, serialize=False)),
                ('service_month', models.DateTimeField()),
                ('electricity_index', models.IntegerField(blank=True, null=True)),
                ('water_index', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('room', models.ForeignKey(db_column='room_id', on_delete=django.db.models.deletion.RESTRICT, to='appartment.room')),
            ],
            options={
                'db_table': 'electric_water_services',
            },
        ),
    ]
