# Generated by Django 5.2.4 on 2025-08-07 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appartment", "0003_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="RoomResident",
            fields=[
                (
                    "room_resident_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("move_in_date", models.DateTimeField(auto_now_add=True)),
                ("move_out_date", models.DateTimeField(blank=True, null=True)),
                (
                    "room",
                    models.ForeignKey(
                        db_column="room_id",
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="residents",
                        to="appartment.room",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        db_column="user_id",
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="appartment.user",
                    ),
                ),
            ],
            options={
                "db_table": "room_resident",
            },
        ),
    ]
