# Generated by Django 5.2.4 on 2025-08-07 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appartment", "0004_roomresident"),
    ]

    operations = [
        migrations.CreateModel(
            name="Bill",
            fields=[
                ("bill_id", models.AutoField(primary_key=True, serialize=False)),
                ("bill_month", models.DateTimeField()),
                (
                    "electricity_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "water_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "additional_service_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("unpaid", "Unpaid"),
                            ("paid", "Paid"),
                            ("overdue", "Overdue"),
                        ],
                        default="unpaid",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("due_date", models.DateTimeField(blank=True, null=True)),
                (
                    "room",
                    models.ForeignKey(
                        db_column="room_id",
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="appartment.room",
                    ),
                ),
            ],
            options={
                "db_table": "bills",
            },
        ),
        migrations.CreateModel(
            name="BillAdditionalService",
            fields=[
                (
                    "bill_additional_service_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("service_month", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("confirmed", "Confirmed"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "additional_service",
                    models.ForeignKey(
                        db_column="additional_service_id",
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="appartment.additionalservice",
                    ),
                ),
                (
                    "bill",
                    models.ForeignKey(
                        blank=True,
                        db_column="bill_id",
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="appartment.bill",
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        blank=True,
                        db_column="room_id",
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="appartment.room",
                    ),
                ),
            ],
            options={
                "db_table": "bill_additional_services",
            },
        ),
        migrations.CreateModel(
            name="RentalPrice",
            fields=[
                (
                    "rental_price_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("effective_date", models.DateTimeField(auto_now_add=True)),
                (
                    "room",
                    models.ForeignKey(
                        db_column="room_id",
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="rental_prices",
                        to="appartment.room",
                    ),
                ),
            ],
            options={
                "db_table": "rental_prices",
            },
        ),
    ]
