# Generated by Django 5.2.4 on 2025-08-07 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appartment", "0005_bill_billadditionalservice_rentalprice"),
    ]

    operations = [
        migrations.CreateModel(
            name="MonthlyMeterReading",
            fields=[
                ("service_id", models.AutoField(primary_key=True, serialize=False)),
                ("service_month", models.DateTimeField()),
                ("electricity_index", models.IntegerField(blank=True, null=True)),
                ("water_index", models.IntegerField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("confirmed", "Confirmed"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        db_column="room_id",
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="appartment.room",
                    ),
                ),
            ],
            options={
                "db_table": "monthly_meter_readings",
            },
        ),
        migrations.CreateModel(
            name="PaymentHistory",
            fields=[
                ("payment_id", models.AutoField(primary_key=True, serialize=False)),
                ("payment_date", models.DateTimeField()),
                ("amount_paid", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("cash", "Cash"),
                            ("bank_transfer", "Bank Transfer"),
                            ("card", "Card"),
                        ],
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "bill",
                    models.ForeignKey(
                        db_column="bill_id",
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="payment_history",
                        to="appartment.bill",
                    ),
                ),
                (
                    "processed_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="processed_by",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="appartment.user",
                    ),
                ),
            ],
            options={
                "db_table": "payment_history",
            },
        ),
    ]
