# Generated by Django 5.2.4 on 2025-08-07 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appartment", "0006_monthlymeterreading_notification_paymenthistory"),
    ]

    operations = [
        migrations.CreateModel(
            name="DraftBill",
            fields=[
                ("draft_bill_id", models.AutoField(primary_key=True, serialize=False)),
                ("bill_month", models.DateField()),
                (
                    "draft_type",
                    models.CharField(
                        choices=[
                            ("ELECTRIC_WATER", "Điện & Nước"),
                            ("SERVICES", "Dịch vụ"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Nháp"),
                            ("SENT", "Đã gửi"),
                            ("CONFIRMED", "Đã xác nhận"),
                            ("REJECTED", "Đã từ chối"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                ("total_amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("details", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="appartment.room",
                    ),
                ),
            ],
            options={
                "db_table": "draft_bills",
                "unique_together": {("room", "bill_month", "draft_type")},
            },
        ),
    ]
