# Generated by Django 5.2.4 on 2025-08-18 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("appartment", "0002_alter_notification_sender_alter_room_status"),
        ("appartment", "0008_notification"),
    ]

    operations = []
