# Generated by Django 5.2.4 on 2025-08-24 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("appartment", "0009_merge_20250819_0122"),
        ("appartment", "0009_merge_20250819_0920"),
    ]

    operations = []
