# Generated by Django 5.2.4 on 2025-08-24 02:29

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appartment", "0010_merge_20250824_0929"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="paymenthistory",
            name="bill",
            field=models.ForeignKey(
                blank=True,
                db_column="bill_id",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="payment_history",
                to="appartment.bill",
            ),
        ),
        migrations.AlterField(
            model_name="rentalprice",
            name="effective_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["sender"], name="notificatio_sender__893501_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["receiver"], name="notificatio_receive_61b4e9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["created_at"], name="notificatio_created_e4c995_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(fields=["status"], name="notificatio_status_fce6f5_idx"),
        ),
    ]
