# Generated by Django 5.2.4 on 2025-08-26 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appartment", "0011_user_is_deleted_alter_paymenthistory_bill_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymenthistory",
            name="order_code",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="paymenthistory",
            name="transaction_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("PENDING", "Pending"),
                    ("SUCCESS", "Success"),
                    ("FAILED", "Failed"),
                ],
                default=None,
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="paymenthistory",
            name="payment_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
